
# ── Async Job Engine ─────────────────────────────────────────────────────────

JOBS_CHANNELS = [
    'default', 'email',
    'webhooks', 'priority',
    'media', 'cleanup', 'metrics'
]

JOBS_DEFAULT_MAX_RETRIES = 0
JOBS_ENGINE_MAX_WORKERS = 10
JOBS_ENGINE_CLAIM_BUFFER = 2
JOBS_ENGINE_CLAIM_BATCH = 5
JOBS_RUNNER_HEARTBEAT_SEC = 5
JOBS_IDLE_TIMEOUT_MS = 60000
JOBS_PAYLOAD_MAX_BYTES = 1048576
JOBS_STREAM_MAXLEN = 100000
JOBS_DEFAULT_BACKOFF_BASE = 2.0
JOBS_DEFAULT_BACKOFF_MAX = 3600
JOBS_REDIS_PREFIX = 'mojo:jobs'
JOBS_WEBHOOK_MAX_RETRIES = 5
JOBS_WEBHOOK_MAX_TIMEOUT = 300
JOBS_WEBHOOK_DEFAULT_TIMEOUT = 10

JOBS_LOCAL_QUEUE_MAXSIZE = 10
