#!/usr/bin/env python
"""
AWS Infrastructure Setup

On first run, prompts for project-specific values and saves them to var/deploy.conf.
Subsequent runs read from that file automatically. AWS credentials come from var/django.conf.

Creates:
  1. Security groups (node, rds, cache) with proper cross-references
  2. EC2 key pair (saved to aws/{project}-{region}.pem)
  3. Aurora PostgreSQL cluster (single instance)
  4. ElastiCache Valkey replication group
  5. EC2 instance with Elastic IP
  6. EC2 environment setup (SSH: packages, nginx, systemd, cron, services)
  7. SES domain verification + DKIM + SNS bounce/complaint/delivery hooks

Usage:
  python aws/deploy.py                    # Interactive - all steps
  python aws/deploy.py --region us-west-2 # Non-interactive region
  python aws/deploy.py --dry-run          # Show what would be created
  python aws/deploy.py --status           # Show current infrastructure status
  python aws/deploy.py --step sg          # Run only one step (sg, key, rds, cache, ec2, ec2-setup, ses)
  python aws/deploy.py --init             # Re-run the setup wizard (overwrite var/deploy.conf)

Credentials: var/django.conf (AWS_KEY, AWS_SECRET)
Deploy config: var/deploy.conf (project name, domain, instance sizes, etc.)
"""
import argparse
import os
import sys
import stat
import time

VAR_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "var")
DEPLOY_CONF = os.path.join(VAR_DIR, "deploy.conf")
DJANGO_CONF = os.path.join(VAR_DIR, "django.conf")


# ── Load key=value conf files ────────────────────────────────────────────────
def _load_conf(path):
    """Load a key=value config file. Strips quotes from values."""
    vals = {}
    if not os.path.exists(path):
        return vals
    with open(path) as f:
        for line in f:
            line = line.strip()
            if "=" in line and not line.startswith("#"):
                key, val = line.split("=", 1)
                vals[key.strip()] = val.strip().strip("'\"")
    return vals


def _save_conf(path, vals):
    """Save a dict to a key=value config file."""
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write("# Auto-generated by aws/deploy.py — edit freely\n")
        for key, val in vals.items():
            f.write(f"{key} = {val}\n")


def load_credentials():
    creds = _load_conf(DJANGO_CONF)
    if "AWS_KEY" not in creds or "AWS_SECRET" not in creds:
        print("ERROR: AWS_KEY and AWS_SECRET must be set in var/django.conf")
        sys.exit(1)
    return creds


# ── Deploy config (var/deploy.conf) ──────────────────────────────────────────
def _detect_project_name():
    """Derive project name from the parent directory name."""
    project_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    name = os.path.basename(project_dir).lower()
    # Strip common prefixes: "mojo-orchestra" → "orchestra", "django-myapp" → "myapp"
    for prefix in ("mojo-", "django-"):
        if name.startswith(prefix):
            name = name[len(prefix):]
    return name.replace("-", "_").replace(" ", "_")


def _generate_password(length=24):
    """Generate a random password for RDS."""
    import secrets
    import string
    chars = string.ascii_letters + string.digits
    return "".join(secrets.choice(chars) for _ in range(length))


def _run_setup_wizard(existing=None):
    """Interactive first-run wizard. Only asks for domain and region, derives the rest."""
    import secrets

    print("\n  ── Deploy Setup Wizard ──")
    print("  This creates var/deploy.conf with your project settings.")
    print("  You can edit the file directly or re-run with --init.\n")

    existing = existing or {}
    project = _detect_project_name()

    # Only two questions
    domain_default = existing.get("DOMAIN", "")
    region_default = existing.get("REGION", "us-west-2")

    domain = input(f"  Production domain{f' [{domain_default}]' if domain_default else ''}: ").strip()
    domain = domain or domain_default
    if not domain:
        print("  ERROR: Domain is required (e.g. maestromojo.com)")
        sys.exit(1)

    region = input(f"  AWS region [{region_default}]: ").strip() or region_default

    # Auto-derive everything else
    vals = {
        "PROJECT": existing.get("PROJECT", project),
        "DOMAIN": domain,
        "REGION": region,
        "DB_NAME": existing.get("DB_NAME", f"mojo_{project}"),
        "DB_USER": existing.get("DB_USER", "postgres"),
        "DB_PASSWORD": existing.get("DB_PASSWORD", _generate_password()),
        "INSTANCE_TYPE": existing.get("INSTANCE_TYPE", "t2.medium"),
        "DB_INSTANCE_CLASS": existing.get("DB_INSTANCE_CLASS", "db.t3.medium"),
        "CACHE_NODE_TYPE": existing.get("CACHE_NODE_TYPE", "cache.t3.medium"),
        "CACHE_NUM_NODES": existing.get("CACHE_NUM_NODES", "2"),
        "EMAIL_FROM": existing.get("EMAIL_FROM", f"noreply@{domain}"),
    }

    _save_conf(DEPLOY_CONF, vals)
    print(f"\n  ✓ Saved to {DEPLOY_CONF}")
    print(f"    Project:  {vals['PROJECT']}")
    print(f"    Domain:   {vals['DOMAIN']}")
    print(f"    Region:   {vals['REGION']}")
    print(f"    Database: {vals['DB_NAME']}")
    print(f"    Email:    {vals['EMAIL_FROM']}")
    print(f"\n  Edit var/deploy.conf to change instance sizes, DB creds, etc.")
    return vals


def load_deploy_config(force_init=False):
    """Load deploy config from var/deploy.conf. Runs wizard if missing."""
    existing = _load_conf(DEPLOY_CONF) if os.path.exists(DEPLOY_CONF) else {}
    if force_init or not existing:
        return _run_setup_wizard(existing)
    return existing


# ── Config (loaded from var/deploy.conf) ─────────────────────────────────────
# These module-level vars are set by _init_config() in main()
PROJECT = ""
DB_NAME = ""
DB_USER = ""
DB_PASSWORD = ""
INSTANCE_TYPE = ""
DB_INSTANCE_CLASS = ""
CACHE_NODE_TYPE = ""
CACHE_NUM_NODES = 2
SES_DOMAIN = ""
SES_FROM_EMAIL = ""


def _init_config(conf):
    """Set module-level config vars from deploy.conf values."""
    global PROJECT, DB_NAME, DB_USER, DB_PASSWORD, INSTANCE_TYPE
    global DB_INSTANCE_CLASS, CACHE_NODE_TYPE, CACHE_NUM_NODES
    global SES_DOMAIN, SES_FROM_EMAIL

    PROJECT = conf.get("PROJECT", "myproject")
    DB_NAME = conf.get("DB_NAME", f"mojo_{PROJECT}")
    DB_USER = conf.get("DB_USER", "postgres")
    DB_PASSWORD = conf.get("DB_PASSWORD", "")
    INSTANCE_TYPE = conf.get("INSTANCE_TYPE", "t2.medium")
    DB_INSTANCE_CLASS = conf.get("DB_INSTANCE_CLASS", "db.t3.medium")
    CACHE_NODE_TYPE = conf.get("CACHE_NODE_TYPE", "cache.t3.medium")
    CACHE_NUM_NODES = int(conf.get("CACHE_NUM_NODES", "2"))
    SES_DOMAIN = conf.get("DOMAIN", "example.com")
    SES_FROM_EMAIL = conf.get("EMAIL_FROM", f"noreply@{SES_DOMAIN}")


def get_boto_session(region, creds):
    import boto3
    return boto3.Session(
        aws_access_key_id=creds["AWS_KEY"],
        aws_secret_access_key=creds["AWS_SECRET"],
        region_name=region,
    )


def get_default_vpc(ec2):
    vpcs = ec2.describe_vpcs(Filters=[{"Name": "isDefault", "Values": ["true"]}])
    if not vpcs["Vpcs"]:
        print("ERROR: No default VPC found in this region.")
        sys.exit(1)
    return vpcs["Vpcs"][0]["VpcId"]


def get_subnets(ec2, vpc_id):
    subnets = ec2.describe_subnets(Filters=[{"Name": "vpc-id", "Values": [vpc_id]}])
    return [s["SubnetId"] for s in subnets["Subnets"]]


def get_subnet_azs(ec2, vpc_id):
    """Get subnets grouped by AZ — need at least 2 AZs for RDS subnet group."""
    subnets = ec2.describe_subnets(Filters=[{"Name": "vpc-id", "Values": [vpc_id]}])
    return subnets["Subnets"]


def tag(name):
    return [{"Key": "Name", "Value": name}, {"Key": "Project", "Value": PROJECT}]


# ── Step 1: Security Groups ──────────────────────────────────────────────────
def setup_security_groups(session, vpc_id, dry_run=False):
    ec2 = session.client("ec2")
    existing = {sg["GroupName"]: sg for sg in ec2.describe_security_groups()["SecurityGroups"]}

    results = {}

    # Node SG (SSH, HTTP, HTTPS from anywhere)
    node_sg_name = f"{PROJECT}-node"
    if node_sg_name in existing:
        print(f"  ✓ {node_sg_name} already exists: {existing[node_sg_name]['GroupId']}")
        results["node"] = existing[node_sg_name]["GroupId"]
    elif dry_run:
        print(f"  [dry-run] Would create SG: {node_sg_name}")
        results["node"] = "sg-DRYRUN-node"
    else:
        resp = ec2.create_security_group(
            GroupName=node_sg_name,
            Description=f"{PROJECT} EC2 node - SSH, HTTP, HTTPS",
            VpcId=vpc_id,
            TagSpecifications=[{"ResourceType": "security-group", "Tags": tag(node_sg_name)}],
        )
        node_sg_id = resp["GroupId"]
        results["node"] = node_sg_id
        for port in [22, 80, 443]:
            ec2.authorize_security_group_ingress(
                GroupId=node_sg_id,
                IpPermissions=[{
                    "IpProtocol": "tcp",
                    "FromPort": port,
                    "ToPort": port,
                    "IpRanges": [{"CidrIp": "0.0.0.0/0"}],
                }],
            )
        print(f"  ✓ Created {node_sg_name}: {node_sg_id} (SSH, HTTP, HTTPS)")

    # RDS SG (PostgreSQL from node SG only)
    rds_sg_name = f"{PROJECT}-rds"
    if rds_sg_name in existing:
        print(f"  ✓ {rds_sg_name} already exists: {existing[rds_sg_name]['GroupId']}")
        results["rds"] = existing[rds_sg_name]["GroupId"]
    elif dry_run:
        print(f"  [dry-run] Would create SG: {rds_sg_name}")
        results["rds"] = "sg-DRYRUN-rds"
    else:
        resp = ec2.create_security_group(
            GroupName=rds_sg_name,
            Description=f"{PROJECT} RDS - PostgreSQL from nodes only",
            VpcId=vpc_id,
            TagSpecifications=[{"ResourceType": "security-group", "Tags": tag(rds_sg_name)}],
        )
        rds_sg_id = resp["GroupId"]
        results["rds"] = rds_sg_id
        ec2.authorize_security_group_ingress(
            GroupId=rds_sg_id,
            IpPermissions=[{
                "IpProtocol": "tcp",
                "FromPort": 5432,
                "ToPort": 5432,
                "UserIdGroupPairs": [{"GroupId": results["node"]}],
            }],
        )
        print(f"  ✓ Created {rds_sg_name}: {rds_sg_id} (5432 from {node_sg_name})")

    # Cache SG (Redis/Valkey from node SG only)
    cache_sg_name = f"{PROJECT}-cache"
    if cache_sg_name in existing:
        print(f"  ✓ {cache_sg_name} already exists: {existing[cache_sg_name]['GroupId']}")
        results["cache"] = existing[cache_sg_name]["GroupId"]
    elif dry_run:
        print(f"  [dry-run] Would create SG: {cache_sg_name}")
        results["cache"] = "sg-DRYRUN-cache"
    else:
        resp = ec2.create_security_group(
            GroupName=cache_sg_name,
            Description=f"{PROJECT} cache - Valkey from nodes only",
            VpcId=vpc_id,
            TagSpecifications=[{"ResourceType": "security-group", "Tags": tag(cache_sg_name)}],
        )
        cache_sg_id = resp["GroupId"]
        results["cache"] = cache_sg_id
        ec2.authorize_security_group_ingress(
            GroupId=cache_sg_id,
            IpPermissions=[{
                "IpProtocol": "tcp",
                "FromPort": 6379,
                "ToPort": 6379,
                "UserIdGroupPairs": [{"GroupId": results["node"]}],
            }],
        )
        print(f"  ✓ Created {cache_sg_name}: {cache_sg_id} (6379 from {node_sg_name})")

    return results


# ── Step 2: Key Pair ──────────────────────────────────────────────────────────
def setup_key_pair(session, region, dry_run=False):
    ec2 = session.client("ec2")
    key_name = PROJECT

    existing = ec2.describe_key_pairs(Filters=[{"Name": "key-name", "Values": [key_name]}])
    if existing["KeyPairs"]:
        print(f"  ✓ Key pair '{key_name}' already exists: {existing['KeyPairs'][0]['KeyPairId']}")
        return key_name

    if dry_run:
        print(f"  [dry-run] Would create key pair: {key_name}")
        return key_name

    resp = ec2.create_key_pair(
        KeyName=key_name,
        KeyType="rsa",
        TagSpecifications=[{"ResourceType": "key-pair", "Tags": tag(key_name)}],
    )

    # Save the private key
    aws_dir = os.path.dirname(os.path.abspath(__file__))
    pem_path = os.path.join(aws_dir, f"{PROJECT}-{region}.pem")
    with open(pem_path, "w") as f:
        f.write(resp["KeyMaterial"])
    os.chmod(pem_path, stat.S_IRUSR)  # 0400
    print(f"  ✓ Created key pair '{key_name}', saved to {pem_path}")
    return key_name


# ── Step 3: Aurora PostgreSQL ─────────────────────────────────────────────────
def setup_rds(session, vpc_id, sg_id, dry_run=False):
    rds = session.client("rds")
    ec2 = session.client("ec2")
    cluster_id = PROJECT

    # Check existing
    try:
        clusters = rds.describe_db_clusters(DBClusterIdentifier=cluster_id)
        c = clusters["DBClusters"][0]
        print(f"  ✓ Aurora cluster '{cluster_id}' already exists: {c['Status']}")
        print(f"    Endpoint: {c['Endpoint']}")
        return c["Endpoint"]
    except rds.exceptions.DBClusterNotFoundFault:
        pass

    if dry_run:
        print(f"  [dry-run] Would create Aurora cluster: {cluster_id}")
        print(f"    Engine: aurora-postgresql 17.4, Instance: {DB_INSTANCE_CLASS}")
        print(f"    DB: {DB_NAME}, User: {DB_USER}")
        return "DRYRUN-endpoint"

    # Create DB subnet group
    subnet_group = f"{PROJECT}-subnets"
    subnets = get_subnets(ec2, vpc_id)
    try:
        rds.describe_db_subnet_groups(DBSubnetGroupName=subnet_group)
        print(f"  ✓ Subnet group '{subnet_group}' already exists")
    except rds.exceptions.DBSubnetGroupNotFoundFault:
        rds.create_db_subnet_group(
            DBSubnetGroupName=subnet_group,
            DBSubnetGroupDescription=f"{PROJECT} Aurora subnets",
            SubnetIds=subnets,
            Tags=tag(subnet_group),
        )
        print(f"  ✓ Created subnet group: {subnet_group}")

    # Create cluster
    print(f"  Creating Aurora PostgreSQL cluster '{cluster_id}'...")
    rds.create_db_cluster(
        DBClusterIdentifier=cluster_id,
        Engine="aurora-postgresql",
        EngineVersion="17.4",
        MasterUsername=DB_USER,
        MasterUserPassword=DB_PASSWORD,
        DatabaseName=DB_NAME,
        DBSubnetGroupName=subnet_group,
        VpcSecurityGroupIds=[sg_id],
        StorageEncrypted=False,
        DeletionProtection=False,
        Tags=tag(cluster_id),
    )
    print(f"  ✓ Cluster creating...")

    # Create single instance
    instance_id = f"{cluster_id}-instance-1"
    print(f"  Creating instance '{instance_id}' ({DB_INSTANCE_CLASS})...")
    rds.create_db_instance(
        DBInstanceIdentifier=instance_id,
        DBClusterIdentifier=cluster_id,
        DBInstanceClass=DB_INSTANCE_CLASS,
        Engine="aurora-postgresql",
        Tags=tag(instance_id),
    )
    print(f"  ✓ Instance creating... (this takes 5-10 minutes)")

    # Wait for cluster to be available
    print("  Waiting for cluster to become available...")
    waiter = rds.get_waiter("db_cluster_available")
    waiter.wait(DBClusterIdentifier=cluster_id, WaiterConfig={"Delay": 30, "MaxAttempts": 40})

    cluster = rds.describe_db_clusters(DBClusterIdentifier=cluster_id)["DBClusters"][0]
    endpoint = cluster["Endpoint"]
    print(f"  ✓ Aurora cluster ready: {endpoint}")
    return endpoint


# ── Step 4: ElastiCache Valkey ────────────────────────────────────────────────
def setup_cache(session, vpc_id, sg_id, dry_run=False):
    ec = session.client("elasticache")
    ec2 = session.client("ec2")
    repl_group = f"{PROJECT}-cache"

    # Check existing
    try:
        groups = ec.describe_replication_groups(ReplicationGroupId=repl_group)
        rg = groups["ReplicationGroups"][0]
        print(f"  ✓ Replication group '{repl_group}' already exists: {rg['Status']}")
        for ng in rg.get("NodeGroups", []):
            ep = ng.get("PrimaryEndpoint", {})
            print(f"    Primary: {ep.get('Address', 'N/A')}:{ep.get('Port', 'N/A')}")
        ep = rg.get("NodeGroups", [{}])[0].get("PrimaryEndpoint", {})
        return ep.get("Address", "")
    except ec.exceptions.ReplicationGroupNotFoundFault:
        pass

    if dry_run:
        print(f"  [dry-run] Would create Valkey replication group: {repl_group}")
        print(f"    Engine: valkey, Nodes: {CACHE_NUM_NODES} x {CACHE_NODE_TYPE}")
        return "DRYRUN-cache-endpoint"

    # Create subnet group
    cache_subnet_group = f"{PROJECT}-cache-subnets"
    subnets = get_subnets(ec2, vpc_id)
    try:
        ec.describe_cache_subnet_groups(CacheSubnetGroupName=cache_subnet_group)
        print(f"  ✓ Cache subnet group '{cache_subnet_group}' already exists")
    except ec.exceptions.CacheSubnetGroupNotFoundFault:
        ec.create_cache_subnet_group(
            CacheSubnetGroupName=cache_subnet_group,
            CacheSubnetGroupDescription=f"{PROJECT} Valkey cache subnets",
            SubnetIds=subnets,
        )
        print(f"  ✓ Created cache subnet group: {cache_subnet_group}")

    print(f"  Creating Valkey replication group '{repl_group}'...")
    ec.create_replication_group(
        ReplicationGroupId=repl_group,
        ReplicationGroupDescription=f"{PROJECT} Valkey cache",
        Engine="valkey",
        CacheNodeType=CACHE_NODE_TYPE,
        NumCacheClusters=CACHE_NUM_NODES,
        CacheSubnetGroupName=cache_subnet_group,
        SecurityGroupIds=[sg_id],
        AutomaticFailoverEnabled=True if CACHE_NUM_NODES > 1 else False,
        TransitEncryptionEnabled=False,
        Tags=tag(repl_group),
    )
    print(f"  ✓ Replication group creating... (this takes 5-10 minutes)")

    # Wait for it
    print("  Waiting for cache to become available...")
    while True:
        time.sleep(30)
        groups = ec.describe_replication_groups(ReplicationGroupId=repl_group)
        status = groups["ReplicationGroups"][0]["Status"]
        print(f"    Status: {status}")
        if status == "available":
            break

    rg = groups["ReplicationGroups"][0]
    ep = rg.get("NodeGroups", [{}])[0].get("PrimaryEndpoint", {})
    endpoint = ep.get("Address", "")
    print(f"  ✓ Valkey cache ready: {endpoint}:{ep.get('Port', 6379)}")
    return endpoint


# ── Step 5: EC2 Instance ──────────────────────────────────────────────────────
def setup_ec2(session, region, vpc_id, sg_id, key_name, dry_run=False):
    ec2 = session.client("ec2")
    instance_name = f"{PROJECT}-1"

    # Check existing
    existing = ec2.describe_instances(
        Filters=[
            {"Name": "tag:Name", "Values": [instance_name]},
            {"Name": "instance-state-name", "Values": ["running", "stopped", "pending"]},
        ]
    )
    for res in existing["Reservations"]:
        for inst in res["Instances"]:
            print(f"  ✓ Instance '{instance_name}' already exists: {inst['InstanceId']} ({inst['State']['Name']})")
            print(f"    Public IP: {inst.get('PublicIpAddress', 'N/A')}")
            return inst["InstanceId"]

    # Get latest AL2023 AMI
    images = ec2.describe_images(
        Owners=["amazon"],
        Filters=[
            {"Name": "name", "Values": ["al2023-ami-2023*-x86_64"]},
            {"Name": "state", "Values": ["available"]},
        ],
    )
    ami = sorted(images["Images"], key=lambda x: x["CreationDate"], reverse=True)[0]
    ami_id = ami["ImageId"]

    if dry_run:
        print(f"  [dry-run] Would create EC2 instance: {instance_name}")
        print(f"    AMI: {ami_id} ({ami['Name']})")
        print(f"    Type: {INSTANCE_TYPE}, Key: {key_name}")
        print(f"    + Elastic IP will be allocated and associated")
        return "i-DRYRUN"

    subnets = get_subnets(ec2, vpc_id)

    # User data runs ec2_bootstrap.sh via curl (no repo needed yet)
    user_data = f"""#!/bin/bash
set -euo pipefail
export PROJ_PATH=/opt/api
export REMOVE_SSM=y
curl -fsSL https://gist.githubusercontent.com/iamojo/6b422432719106aef8d713fb9a24ed67/raw/ec2_django_mojo_install.sh | bash
"""

    print(f"  Launching EC2 instance '{instance_name}'...")
    resp = ec2.run_instances(
        ImageId=ami_id,
        InstanceType=INSTANCE_TYPE,
        KeyName=key_name,
        SecurityGroupIds=[sg_id],
        SubnetId=subnets[0],
        MinCount=1,
        MaxCount=1,
        UserData=user_data,
        TagSpecifications=[{"ResourceType": "instance", "Tags": tag(instance_name)}],
        BlockDeviceMappings=[{
            "DeviceName": "/dev/xvda",
            "Ebs": {"VolumeSize": 30, "VolumeType": "gp3"},
        }],
    )
    instance_id = resp["Instances"][0]["InstanceId"]
    print(f"  ✓ Instance launching: {instance_id}")

    # Wait for running
    print("  Waiting for instance to be running...")
    waiter = ec2.get_waiter("instance_running")
    waiter.wait(InstanceIds=[instance_id])

    # Allocate and associate Elastic IP
    print("  Allocating Elastic IP...")
    eip = ec2.allocate_address(
        Domain="vpc",
        TagSpecifications=[{"ResourceType": "elastic-ip", "Tags": tag(f"{instance_name}-eip")}],
    )
    elastic_ip = eip["PublicIp"]
    ec2.associate_address(
        AllocationId=eip["AllocationId"],
        InstanceId=instance_id,
    )
    print(f"  ✓ Elastic IP: {elastic_ip} (AllocationId: {eip['AllocationId']})")

    print(f"  ✓ Instance running: {instance_id}")
    print(f"    Elastic IP: {elastic_ip}")
    print(f"    SSH: ssh -i aws/{PROJECT}-{region}.pem ec2-user@{elastic_ip}")
    return instance_id


# ── Step 6: EC2 Setup (SSH in and configure) ─────────────────────────────────
def setup_ec2_environment(session, region, dry_run=False):
    """SSH into EC2 and run the full setup: ec2_install.sh, deploy app, enable services."""
    ec2 = session.client("ec2")
    instance_name = f"{PROJECT}-1"

    # Find instance
    existing = ec2.describe_instances(
        Filters=[
            {"Name": "tag:Name", "Values": [instance_name]},
            {"Name": "instance-state-name", "Values": ["running"]},
        ]
    )
    instance_ip = None
    for res in existing["Reservations"]:
        for inst in res["Instances"]:
            instance_ip = inst.get("PublicIpAddress")
    if not instance_ip:
        print("  ERROR: No running instance found. Run --step ec2 first.")
        return

    pem_file = os.path.join(os.path.dirname(os.path.abspath(__file__)), f"{PROJECT}-{region}.pem")
    if not os.path.exists(pem_file):
        print(f"  ERROR: Key file not found: {pem_file}")
        return

    ssh_cmd = f"ssh -i {pem_file} -o StrictHostKeyChecking=no ec2-user@{instance_ip}"

    if dry_run:
        print(f"  [dry-run] Would SSH to {instance_ip} and run setup")
        print(f"  Commands: clone repo, run ec2_install.sh, configure services")
        return

    print(f"  EC2 instance: {instance_ip}")
    print(f"  This step will:")
    print(f"    1. Clone the repo to /opt/api (if not present)")
    print(f"    2. Run aws/ec2_deploy.sh (project configs, nginx, systemd, crons)")
    print()
    print(f"  NOTE: ec2_bootstrap.sh should have already run via user_data on first boot.")
    print(f"        If not, SSH in and run it first:")
    print(f"        curl -fsSL https://gist.githubusercontent.com/iamojo/6b422432719106aef8d713fb9a24ed67/raw/ec2_django_mojo_install.sh | sudo bash")
    print()
    print(f"  SSH command for manual setup:")
    print(f"    {ssh_cmd}")
    print()

    # Build remote setup script
    setup_script = f"""
set -euo pipefail
echo "=== Orchestra EC2 Deploy ==="

# Clone repo if not present
if [[ ! -d /opt/api/.git ]]; then
    echo "Cloning repository..."
    cd /opt
    git clone git@github.com:NativeMojo/mojo-orchestra.git api
    cd /opt/api
else
    echo "Repo already exists, pulling latest..."
    cd /opt/api
    git pull
fi

# Run the project deploy script
echo "Running ec2_deploy.sh..."
sudo PROJ_PATH=/opt/api bash /opt/api/aws/ec2_deploy.sh

echo "=== Deploy Complete ==="
echo "Remaining: configure var/django.conf, var/profile, run migrations, certbot, enable services"
"""

    print("  Running setup via SSH...")
    import subprocess
    result = subprocess.run(
        ["ssh", "-i", pem_file, "-o", "StrictHostKeyChecking=no", f"ec2-user@{instance_ip}",
         "bash -s"],
        input=setup_script,
        capture_output=True,
        text=True,
        timeout=600,
    )
    print(result.stdout)
    if result.returncode != 0:
        print(f"  WARN: Setup exited with code {result.returncode}")
        if result.stderr:
            print(f"  stderr: {result.stderr[-500:]}")
    else:
        print(f"  ✓ EC2 setup complete")


# ── Step 7: SES Domain Verification + DKIM ───────────────────────────────────
def setup_ses(session, region, dry_run=False):
    """Verify domain in SES and enable DKIM signing."""
    ses = session.client("ses")

    # Check current domain verification status
    try:
        attrs = ses.get_identity_verification_attributes(Identities=[SES_DOMAIN])
        status = attrs["VerificationAttributes"].get(SES_DOMAIN, {}).get("VerificationStatus")
    except Exception:
        status = None

    if status == "Success":
        print(f"  ✓ Domain '{SES_DOMAIN}' already verified")
    elif dry_run:
        print(f"  [dry-run] Would verify domain: {SES_DOMAIN}")
        print(f"  [dry-run] Would enable DKIM for: {SES_DOMAIN}")
        return
    else:
        if status == "Pending":
            print(f"  ⧖ Domain '{SES_DOMAIN}' verification pending — check DNS records below")
        else:
            print(f"  Verifying domain '{SES_DOMAIN}'...")
            ses.verify_domain_identity(Domain=SES_DOMAIN)
            print(f"  ✓ Domain verification initiated")

        # Get the TXT verification token
        attrs = ses.get_identity_verification_attributes(Identities=[SES_DOMAIN])
        token = attrs["VerificationAttributes"].get(SES_DOMAIN, {}).get("VerificationToken", "")
        if token:
            print(f"\n  Add this DNS TXT record to verify domain ownership:")
            print(f"    Name:  _amazonses.{SES_DOMAIN}")
            print(f"    Type:  TXT")
            print(f"    Value: {token}")

    # DKIM
    try:
        dkim_attrs = ses.get_identity_dkim_attributes(Identities=[SES_DOMAIN])
        dkim_status = dkim_attrs["DkimAttributes"].get(SES_DOMAIN, {}).get("DkimVerificationStatus")
        dkim_tokens = dkim_attrs["DkimAttributes"].get(SES_DOMAIN, {}).get("DkimTokens", [])
    except Exception:
        dkim_status = None
        dkim_tokens = []

    if dkim_status == "Success":
        print(f"  ✓ DKIM already verified for '{SES_DOMAIN}'")
    else:
        if not dkim_tokens:
            print(f"\n  Enabling DKIM for '{SES_DOMAIN}'...")
            resp = ses.verify_domain_dkim(Domain=SES_DOMAIN)
            dkim_tokens = resp.get("DkimTokens", [])
            print(f"  ✓ DKIM initiated")

        if dkim_tokens:
            print(f"\n  Add these 3 DNS CNAME records for DKIM:")
            for token in dkim_tokens:
                print(f"    Name:  {token}._domainkey.{SES_DOMAIN}")
                print(f"    Type:  CNAME")
                print(f"    Value: {token}.dkim.amazonses.com")
                print()

    # MAIL FROM (optional but improves deliverability)
    mail_from_domain = f"mail.{SES_DOMAIN}"
    try:
        mf_attrs = ses.get_identity_mail_from_domain_attributes(Identities=[SES_DOMAIN])
        current_mf = mf_attrs["MailFromDomainAttributes"].get(SES_DOMAIN, {}).get("MailFromDomain", "")
    except Exception:
        current_mf = ""

    if current_mf == mail_from_domain:
        print(f"  ✓ MAIL FROM already set to '{mail_from_domain}'")
    else:
        if not dry_run:
            ses.set_identity_mail_from_domain(
                Identity=SES_DOMAIN,
                MailFromDomain=mail_from_domain,
            )
        print(f"  ✓ MAIL FROM set to '{mail_from_domain}'")
        print(f"\n  Add these DNS records for MAIL FROM:")
        print(f"    Name:  {mail_from_domain}")
        print(f"    Type:  MX")
        print(f"    Value: 10 feedback-smtp.{region}.amazonses.com")
        print()
        print(f"    Name:  {mail_from_domain}")
        print(f"    Type:  TXT")
        print(f"    Value: \"v=spf1 include:amazonses.com ~all\"")

    # SNS topics for bounce/complaint/delivery notifications
    sns = session.client("sns")
    base_domain = SES_DOMAIN.replace(".", "-")
    webhook_base = f"https://{SES_DOMAIN}/api/email/sns"
    topic_types = {
        "bounce": f"ses-{base_domain}-bounce",
        "complaint": f"ses-{base_domain}-complaint",
        "delivery": f"ses-{base_domain}-delivery",
    }

    print(f"\n  Setting up SNS notification topics...")
    topic_arns = {}
    for notif_type, topic_name in topic_types.items():
        if dry_run:
            print(f"  [dry-run] Would create SNS topic: {topic_name}")
            continue

        # create_topic is idempotent — returns existing ARN if already exists
        resp = sns.create_topic(
            Name=topic_name,
            Tags=[{"Key": "Project", "Value": PROJECT}, {"Key": "Type", "Value": notif_type}],
        )
        arn = resp["TopicArn"]
        topic_arns[notif_type] = arn
        print(f"  ✓ SNS topic: {topic_name} ({arn})")

        # Map topic to SES identity notifications
        ses.set_identity_notification_topic(
            Identity=SES_DOMAIN,
            NotificationType=notif_type.capitalize(),
            SnsTopic=arn,
        )
        print(f"    → mapped to SES {notif_type} notifications")

        # Subscribe our webhook endpoint (idempotent)
        endpoint = f"{webhook_base}/{notif_type}"
        sns.subscribe(
            TopicArn=arn,
            Protocol="https",
            Endpoint=endpoint,
            ReturnSubscriptionArn=True,
        )
        print(f"    → subscribed: {endpoint}")

    if not dry_run and topic_arns:
        # Disable email notifications (we use SNS instead)
        for notif_type in ["Bounce", "Complaint", "Delivery"]:
            ses.set_identity_headers_in_notifications_enabled(
                Identity=SES_DOMAIN,
                NotificationType=notif_type,
                Enabled=True,
            )
        ses.set_identity_feedback_forwarding_enabled(
            Identity=SES_DOMAIN,
            ForwardingEnabled=False,
        )
        print(f"  ✓ Email forwarding disabled (using SNS only)")
        print(f"\n  NOTE: SNS subscriptions require confirmation.")
        print(f"    Your server must be running at {webhook_base}/* to auto-confirm.")
        print(f"    django-mojo handles confirmation automatically.")

    # Check sandbox status
    try:
        account = ses.get_send_quota()
        max_24hr = account.get("Max24HourSend", 0)
        if max_24hr <= 200:
            print(f"\n  ⚠ SES is in SANDBOX mode (limit: {max_24hr}/day)")
            print(f"    You can only send to verified email addresses.")
            print(f"    Request production access in the AWS console:")
            print(f"    https://{region}.console.aws.amazon.com/ses/home?region={region}#/account")
        else:
            print(f"\n  ✓ SES production access (limit: {max_24hr}/day)")
    except Exception:
        pass

    print(f"\n  From address: {SES_FROM_EMAIL}")
    print(f"  Set EMAIL_FROM = \"{SES_FROM_EMAIL}\" in var/django.conf")


# ── Status ────────────────────────────────────────────────────────────────────
def show_status(session, region):
    ec2 = session.client("ec2")
    rds = session.client("rds")
    ec = session.client("elasticache")

    print(f"\n{'='*60}")
    print(f"  Mojo Orchestra — {region}")
    print(f"{'='*60}")

    # Security groups
    print("\n── Security Groups ──")
    for name in [f"{PROJECT}-node", f"{PROJECT}-rds", f"{PROJECT}-cache"]:
        sgs = ec2.describe_security_groups(Filters=[{"Name": "group-name", "Values": [name]}])
        if sgs["SecurityGroups"]:
            sg = sgs["SecurityGroups"][0]
            print(f"  ✓ {name}: {sg['GroupId']}")
        else:
            print(f"  ✗ {name}: not found")

    # Key pair
    print("\n── Key Pair ──")
    keys = ec2.describe_key_pairs(Filters=[{"Name": "key-name", "Values": [PROJECT]}])
    if keys["KeyPairs"]:
        print(f"  ✓ {PROJECT}: {keys['KeyPairs'][0]['KeyPairId']}")
    else:
        print(f"  ✗ {PROJECT}: not found")

    # RDS
    print("\n── Aurora PostgreSQL ──")
    try:
        clusters = rds.describe_db_clusters(DBClusterIdentifier=PROJECT)
        c = clusters["DBClusters"][0]
        print(f"  ✓ {PROJECT}: {c['Status']}")
        print(f"    Endpoint: {c['Endpoint']}")
        print(f"    Port: {c['Port']} | DB: {c.get('DatabaseName', 'N/A')}")
    except rds.exceptions.DBClusterNotFoundFault:
        print(f"  ✗ {PROJECT}: not found")

    # ElastiCache
    print("\n── Valkey Cache ──")
    try:
        groups = ec.describe_replication_groups(ReplicationGroupId=f"{PROJECT}-cache")
        rg = groups["ReplicationGroups"][0]
        print(f"  ✓ {PROJECT}-cache: {rg['Status']}")
        for ng in rg.get("NodeGroups", []):
            ep = ng.get("PrimaryEndpoint", {})
            print(f"    Primary: {ep.get('Address', 'N/A')}:{ep.get('Port', 'N/A')}")
    except ec.exceptions.ReplicationGroupNotFoundFault:
        print(f"  ✗ {PROJECT}-cache: not found")

    # SES
    print("\n── SES Email ──")
    try:
        ses = session.client("ses")
        attrs = ses.get_identity_verification_attributes(Identities=[SES_DOMAIN])
        v_status = attrs["VerificationAttributes"].get(SES_DOMAIN, {}).get("VerificationStatus", "not configured")
        dkim_attrs = ses.get_identity_dkim_attributes(Identities=[SES_DOMAIN])
        d_status = dkim_attrs["DkimAttributes"].get(SES_DOMAIN, {}).get("DkimVerificationStatus", "not configured")
        quota = ses.get_send_quota()
        max_send = quota.get("Max24HourSend", 0)
        sent = quota.get("SentLast24Hours", 0)
        mode = "production" if max_send > 200 else "sandbox"
        print(f"  Domain: {SES_DOMAIN} — verification: {v_status}, DKIM: {d_status}")
        print(f"  Mode: {mode} | Sent: {int(sent)}/{int(max_send)} (24hr)")
    except Exception as e:
        print(f"  ✗ Could not check SES: {e}")

    # SNS topics
    print("\n── SNS Topics ──")
    try:
        sns_client = session.client("sns")
        base_domain = SES_DOMAIN.replace(".", "-")
        for notif_type in ["bounce", "complaint", "delivery"]:
            topic_name = f"ses-{base_domain}-{notif_type}"
            # List subscriptions by looking up the topic
            try:
                topic_arn = f"arn:aws:sns:{region}:{session.client('sts').get_caller_identity()['Account']}:{topic_name}"
                subs = sns_client.list_subscriptions_by_topic(TopicArn=topic_arn)
                sub_count = len(subs.get("Subscriptions", []))
                sub_status = subs["Subscriptions"][0]["SubscriptionArn"] if sub_count else "none"
                confirmed = "confirmed" if sub_status.startswith("arn:") else sub_status
                print(f"  ✓ {topic_name}: {sub_count} subscription(s) ({confirmed})")
            except Exception:
                print(f"  ✗ {topic_name}: not found")
    except Exception as e:
        print(f"  ✗ Could not check SNS: {e}")

    # Elastic IPs
    print("\n── Elastic IPs ──")
    eips = ec2.describe_addresses(Filters=[{"Name": "tag:Project", "Values": [PROJECT]}])
    if eips["Addresses"]:
        for eip in eips["Addresses"]:
            name = ""
            for t in eip.get("Tags", []):
                if t["Key"] == "Name":
                    name = t["Value"]
            print(f"  ✓ {name}: {eip['PublicIp']} → {eip.get('InstanceId', 'unattached')}")
    else:
        print(f"  ✗ No elastic IPs found")

    # EC2
    print("\n── EC2 Instances ──")
    instances = ec2.describe_instances(
        Filters=[
            {"Name": "tag:Project", "Values": [PROJECT]},
            {"Name": "instance-state-name", "Values": ["running", "stopped", "pending"]},
        ]
    )
    found = False
    for res in instances["Reservations"]:
        for inst in res["Instances"]:
            name = ""
            for t in inst.get("Tags", []):
                if t["Key"] == "Name":
                    name = t["Value"]
            print(f"  ✓ {name}: {inst['InstanceId']} | {inst['InstanceType']} | {inst['State']['Name']}")
            print(f"    IP: {inst.get('PublicIpAddress', 'N/A')}")
            found = True
    if not found:
        print(f"  ✗ No instances found")

    print()


# ── Generate var/django.conf for production ───────────────────────────────────
def generate_django_conf(region, db_endpoint, cache_endpoint):
    """Print the var/django.conf settings for the production server."""
    print(f"\n{'='*60}")
    print("  var/django.conf for production server")
    print(f"{'='*60}")
    print(f"""
REST_AUTO_PREFIX = True
AWS_REGION = "{region}"
AWS_KEY = "<your-aws-key>"
AWS_SECRET = "<your-aws-secret>"

DATABASE_HOST = "{db_endpoint}"
DATABASE_PORT = "5432"
DATABASE_NAME = "{DB_NAME}"
DATABASE_USER = "{DB_USER}"
DATABASE_PASSWORD = "{DB_PASSWORD}"

REDIS_HOST = "{cache_endpoint}"
REDIS_PORT = "6379"

EMAIL_FROM = "{SES_FROM_EMAIL}"
""")


# ── Main ──────────────────────────────────────────────────────────────────────
STEPS = ["sg", "key", "rds", "cache", "ec2", "ec2-setup", "ses"]


def main():
    parser = argparse.ArgumentParser(description="Deploy project infrastructure to AWS")
    parser.add_argument("--region", help="AWS region (overrides deploy.conf)")
    parser.add_argument("--dry-run", action="store_true", help="Show what would be created")
    parser.add_argument("--status", action="store_true", help="Show current infrastructure")
    parser.add_argument("--step", choices=STEPS, help="Run only one step")
    parser.add_argument("--yes", "-y", action="store_true", help="Skip confirmation prompts")
    parser.add_argument("--init", action="store_true", help="Re-run setup wizard (overwrite var/deploy.conf)")
    args = parser.parse_args()

    # Load or create deploy config
    conf = load_deploy_config(force_init=args.init)
    _init_config(conf)

    if args.init:
        print("\n  Config saved. Run again without --init to deploy.")
        return

    creds = load_credentials()

    region = args.region or conf.get("REGION", "us-west-2")
    session = get_boto_session(region, creds)

    if args.status:
        show_status(session, region)
        return

    print(f"\n  {PROJECT} AWS Deploy → {region}")
    print(f"  {'(DRY RUN)' if args.dry_run else ''}")
    print(f"  {'='*50}\n")

    if not args.yes and not args.dry_run:
        confirm = input(f"  Deploy to {region}? [y/N] ")
        if confirm.lower() != "y":
            print("  Aborted.")
            return

    ec2 = session.client("ec2")
    vpc_id = get_default_vpc(ec2)
    print(f"  Using default VPC: {vpc_id}\n")

    steps_to_run = [args.step] if args.step else STEPS
    sg_ids = {}
    db_endpoint = ""
    cache_endpoint = ""

    # Always load existing SG IDs if skipping SG step
    if "sg" not in steps_to_run:
        ec2_client = session.client("ec2")
        for name_suffix in ["node", "rds", "cache"]:
            sg_name = f"{PROJECT}-{name_suffix}"
            sgs = ec2_client.describe_security_groups(Filters=[{"Name": "group-name", "Values": [sg_name]}])
            if sgs["SecurityGroups"]:
                sg_ids[name_suffix] = sgs["SecurityGroups"][0]["GroupId"]

    for step in steps_to_run:
        if step == "sg":
            print("── Step 1: Security Groups ──")
            sg_ids = setup_security_groups(session, vpc_id, dry_run=args.dry_run)
            print()

        elif step == "key":
            print("── Step 2: Key Pair ──")
            setup_key_pair(session, region, dry_run=args.dry_run)
            print()

        elif step == "rds":
            print("── Step 3: Aurora PostgreSQL ──")
            if "rds" not in sg_ids:
                print("  ERROR: RDS security group not found. Run --step sg first.")
                continue
            db_endpoint = setup_rds(session, vpc_id, sg_ids["rds"], dry_run=args.dry_run)
            print()

        elif step == "cache":
            print("── Step 4: Valkey Cache ──")
            if "cache" not in sg_ids:
                print("  ERROR: Cache security group not found. Run --step sg first.")
                continue
            cache_endpoint = setup_cache(session, vpc_id, sg_ids["cache"], dry_run=args.dry_run)
            print()

        elif step == "ec2":
            print("── Step 5: EC2 Instance ──")
            if "node" not in sg_ids:
                print("  ERROR: Node security group not found. Run --step sg first.")
                continue
            key_name = PROJECT
            setup_ec2(session, region, vpc_id, sg_ids["node"], key_name, dry_run=args.dry_run)
            print()

        elif step == "ec2-setup":
            print("── Step 6: EC2 Environment Setup ──")
            setup_ec2_environment(session, region, dry_run=args.dry_run)
            print()

        elif step == "ses":
            print("── Step 7: SES Email ──")
            setup_ses(session, region, dry_run=args.dry_run)
            print()

    if db_endpoint and cache_endpoint:
        generate_django_conf(region, db_endpoint, cache_endpoint)

    print("  Done! Run `python aws/deploy.py --status` to check infrastructure.")


if __name__ == "__main__":
    main()
