# Everything you need to fill in var/django.conf and point DNS.

output "point_dns_at" {
  description = "A records for every hostname this environment serves — the NLB's static addresses, or the single node's Elastic IP."
  value       = var.use_nlb ? module.nlb[0].public_ips : module.nodes.public_ips
}

output "ssh_targets" {
  description = "Per-node public addresses for SSH."
  value       = zipmap(module.nodes.hostnames, module.nodes.public_ips)
}

output "primary_balancer_host" {
  description = <<-EOT
    The node sitting in the certbot-targets group — where HTTP-01 challenges
    land. This is NOT a var/django.conf key: nothing reads PRIMARY_BALANCER_HOST
    any more. Fleet certificates are issued by dnsman over DNS-01 and installed
    per node by mojo.apps.edge; this output only matters if something on this
    environment still validates over HTTP-01.
  EOT
  value       = module.nodes.gatekeeper_hostname
}

output "db_writer_endpoint" { value = module.data.db_writer_endpoint }
output "db_reader_endpoint" { value = module.data.db_reader_endpoint }
output "db_name" { value = module.data.db_name }

output "db_password" {
  value     = module.data.db_password
  sensitive = true
}

output "cache_primary_endpoint" { value = module.data.cache_primary_endpoint }
output "cache_reader_endpoint" { value = module.data.cache_reader_endpoint }

output "alarm_topic_arn" {
  description = <<-EOT
    Goes in AWS_CLOUDWATCH_ALARM_TOPIC_ARNS — but only when this root owns the
    alarms. With enable_alarms false (how both shipped tfvars come, because the
    admin portal owns alarms on a managed installation) there is no topic and
    this returns an EMPTY STRING. Use the portal's operations topic instead.
  EOT
  value       = module.observability.alarm_topic_arn
}

# Key names match aws/deploy.py's managed block — the set config/settings/
# prod/db.py actually reads (DATABASE_*/REDIS_*) and mojo's redis client
# consumes (REDIS_SERVER/REDIS_SCHEME). The reader endpoint is deliberately
# not in the fragment: nothing reads a reader key from django.conf, and a dead
# key in the conf masquerades as wiring. It stays available as the
# db_reader_endpoint output above.
output "django_conf_fragment" {
  description = "Paste into var/django.conf, then add DATABASE_PASSWORD from `tofu output -raw db_password`."
  sensitive   = true
  value       = <<EOT
# ── generated by opentofu for ${var.project}/${var.env} ──
DATABASE_HOST = "${module.data.db_writer_endpoint}"
DATABASE_PORT = "5432"
DATABASE_NAME = "${module.data.db_name}"
DATABASE_USER = "postgres"
REDIS_SERVER = "${module.data.cache_primary_endpoint}"
REDIS_PORT = "6379"
# this cache is created with transit encryption REQUIRED (modules/data) —
# unlike deploy.py's, whose managed block pins REDIS_SCHEME = "redis"
REDIS_SCHEME = "rediss"
AWS_REGION = "${var.region}"
%{if var.enable_alarms~}
AWS_CLOUDWATCH_ALARM_TOPIC_ARNS = "${module.observability.alarm_topic_arn}"
%{else~}
# AWS_CLOUDWATCH_ALARM_TOPIC_ARNS is deliberately absent: enable_alarms is
# false, so the admin portal owns the alarms and writes its own operations
# topic ARN into this key. A value from here would point the ingest at a
# topic nothing publishes to.
%{endif~}
EOT
}
