# Everything you need to fill in var/django.conf and point DNS.

output "point_dns_at" {
  description = "A records for every hostname this environment serves — the NLB's static addresses, or the single node's Elastic IP."
  value       = var.use_nlb ? module.nlb[0].public_ips : module.nodes.public_ips
}

output "ssh_targets" {
  description = "Per-node public addresses for SSH."
  value       = zipmap(module.nodes.hostnames, module.nodes.public_ips)
}

output "primary_balancer_host" {
  description = <<-EOT
    Set PRIMARY_BALANCER_HOST in var/django.conf to exactly this. It must name
    the node sitting in the certbot-targets group, or the node that receives
    ACME challenges will behave as a replica and never publish the renewed
    lineage — certificates then stop renewing silently.
  EOT
  value       = module.nodes.gatekeeper_hostname
}

output "db_writer_endpoint" { value = module.data.db_writer_endpoint }
output "db_reader_endpoint" { value = module.data.db_reader_endpoint }
output "db_name" { value = module.data.db_name }

output "db_password" {
  value     = module.data.db_password
  sensitive = true
}

output "cache_primary_endpoint" { value = module.data.cache_primary_endpoint }
output "cache_reader_endpoint" { value = module.data.cache_reader_endpoint }

output "alarm_topic_arn" {
  description = "Goes in AWS_CLOUDWATCH_ALARM_TOPIC_ARNS."
  value       = module.observability.alarm_topic_arn
}

output "django_conf_fragment" {
  description = "Paste into var/django.conf, then add the DB password from `tofu output -raw db_password`."
  sensitive   = true
  value       = <<-EOT
    # ── generated by opentofu for ${var.project}/${var.env} ──
    DB_HOST = "${module.data.db_writer_endpoint}"
    DB_READ_HOST = "${module.data.db_reader_endpoint}"
    DB_NAME = "${module.data.db_name}"
    DB_USER = "postgres"
    REDIS_HOST = "${module.data.cache_primary_endpoint}"
    REDIS_PORT = 6379
    REDIS_SSL = True
    AWS_REGION = "${var.region}"
    AWS_CLOUDWATCH_ALARM_TOPIC_ARNS = "${module.observability.alarm_topic_arn}"
    PRIMARY_BALANCER_HOST = "${module.nodes.gatekeeper_hostname}"
  EOT
}
